### PR TITLE
Update sdk and local tableland

### PR DESCRIPTION
**Pull request by asutula**
Mostly fixes with `helpers`. There are two tests failing and i'm not sure how to correct them. I think the problem is that previously the error related to an invalid chain id was raised with `console.error()` within the CLI code and the tests were able to test that correctly. But now the invalid chain id error is thrown from within the SDK code, and the test doesn't handle that correctly.

### CODE REVIEW

**Comment by carsonfarmer** [comment]
Should we also sneak in those dev dep updates as well? Might as well, right?

**Comment by asutula** [comment]
Which dev dep updates do you mean @carsonfarmer ?

**Comment by awmuncy** [comment]
@asutula I just moved the PR for my `ens` branch from draft into Ready for Review. I've incorporated the changes to how the SDK exports helpers, and managed to fix that test. See here: https://github.com/tablelandnetwork/js-tableland-cli/pull/158

The changes in that branch a pretty involved, so I think it might make sense to merge that one instead of merging this one then dealing with merge conflicts.

**Comment by asutula** [comment]
Ah ok @awmuncy, that works for me. I hope we can get it merged soon!

**Comment by carsonfarmer** [comment]
Ha, ok that's awesome @awmuncy. I was just about to dig in. For the most part, it looks like it was just a case of moving the try/catch up and then updating the error message checks in the tests?

**Comment by awmuncy** [comment]
> 

Yep! Though I actually caught the error in the CLI's scripts and spit out the original error message, which meant I didn't have to update the tests.

**Comment by carsonfarmer** [comment]
> Which dev dep updates do you mean @carsonfarmer ?

Just the ones dependabot has in the queue. Might as well pull them into this PR manually.

**Review by carsonfarmer — APPROVED** [review]
With the updates in #178 this looks good. It also looks like there are going to be a ton of conflicts with #158, so perhaps we defer to that PR for updates due to upgrading the SDK?

**Comment by asutula** [comment]
Yea, was planning on just closing this in favor of #158

**Pull request closed without merging**
