### PR TITLE
Fix a regression with the write command by using the new getWallet helper

### PR DESCRIPTION
**Pull request by datadanne**
I just installed the latest version of the cli and noticed that the `write` command had stopped working. I read through the `tableland write --help` readme but didn't find anything useful so I skimmed through the diff for the v3 releases for the cli and the sdk and noticed that `checkNetwork` now assumes that the signer has a provider attached to it but that the write wasn't updated to use the `getWallet` helper which initializes and sets a provider. Does this solution make sense?

### CODE REVIEW

**Comment by joewagner** [comment]
This looks good to me, but I'll let @carsonfarmer weigh in before approving

**Comment by datadanne** [comment]
Ah it looks like my vim-prettier plugin didn't pick up the correct prettier config for some reason. Fixed that and force-pushed a new commit!

**Comment by carsonfarmer** [comment]
Looks good to me. This is actually something we should have included in the previous PR (just merged), so good catch @datadanne. I've just pushed an update that resolves a merge conflict, can you just take a quick look and confirm that merge went as expected @datadanne? If you give me a 👍 , I'll merge and release asap.

**Comment by datadanne** [comment]
> Looks good to me. This is actually something we should have included in the previous PR (just merged), so good catch @datadanne. I've just pushed an update that resolves a merge conflict, can you just take a quick look and confirm that merge went as expected @datadanne? If you give me a 👍 , I'll merge and release asap.

The merge lgtm!

**Review by carsonfarmer — APPROVED** [review]
Thanks for the quick fix and thorough review folks. This looks good to me, going to approve and merge now.

**Pull request merged**
