### PR TITLE
Adds support for auto-publish to npm

### LINKED ISSUE #11: Create CI flow to publish to NPM
Like https://github.com/textileio/go-threads/blob/master/.github/workflows/publish-grpc-libs.yml

### PR DESCRIPTION
**Pull request by carsonfarmer**
Fixes #11

### CODE REVIEW

**Comment by carsonfarmer** [comment]
This adds support for a nicer publish flow. Now, when someone changes the version in package.json to X.Y.Z and pushes a commit with the message "Release X.Y.Z, the new Publish action will create a new tag vX.Y.Z and publish the package to the npm registry.

**Review by joewagner — APPROVED** [review]
This is awesome, let's do it!  The only question I can come up with is what happens with the `latest` tag we have been using?  Even if we have to give up using `latest` I think this is a big improvement.

**Comment by carsonfarmer** [comment]
This will automatically publish over latest, so it will get the latest tag. Which I think is right. If we want to do some "next" releases, or "dev" releases, then I think this should actually be a manual thing for now. Having said that, we _could_ consider automatic that process as well, and having a separate action that watches for -dev versions and publishes under a different tag?

**Comment by joewagner** [comment]
> This will automatically publish over latest, so it will get the latest tag. Which I think is right. If we want to do some "next" releases, or "dev" releases, then I think this should actually be a manual thing for now. Having said that, we _could_ consider automatic that process as well, and having a separate action that watches for -dev versions and publishes under a different tag?

Making publishing dev, or others, manual seems good for now.  It's been very rare so far, so doing this as is seems great!

**Pull request merged**
